name: "\U0001F41B Bug Report"
description: "If something isn't working as expected \U0001F914"
labels: ["bug, pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## We use GitHub Issues to track bug reports, feature requests and regressions
        
        **NOTE:** You don't need to answer questions that you know that aren't relevant.
      
        ---

  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: "Please search [here](../issues?q=is%3Aissue) to see if an issue already exists for the bug you encountered"
      options:
      - label: "I have searched the existing issues"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Current behavior"
      description: "How the issue manifests?"

  - type: textarea
      validations:
      required: true
    attributes:
      label: "Steps to reproduce"
      description: |
        How the issue manifests?
      placeholder: |
        1. `yarn install`
        2. `yarn dev`
        3. See error...
        
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happened (or code)"

  - type: markdown
    attributes:
      value: |
        ---
        
  - type: input
    attributes:
      label: "Node.js version"
      description: "Which version of Node.js are you using?"
      placeholder: "14.17.6"

  - type: dropdown
    attributes:
      label: "In which operating systems have you tested?"
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: textarea
    attributes:
      label: "Other"
      description: |
        Anything else relevant? eg: Logs, OS version, IDE, package manager, etc.
        **Tip:** You can attach images, recordings or log files by clicking this area to highlight it and then dragging files in
